name: Admin Panel

on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./admin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './admin/package-lock.json'
    - name: Install npm dependencies
      run: npm ci
    - name: Build React App
      run: |
        echo "Starting build process..."
        CI=false npm run build
        echo "Build completed"
        ls -la dist/
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ubuntu/admin"
          EXCLUDE: "/node_modules/, .env, .git*, package-lock.json"