name: Client

on:
  push:
    branches: ["main"]

defaults:
  run:
    working-directory: ./client
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'
      - name: Install npm dependencies
        run: npm ci
      - name: Run build task
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "client/.next/"  # Next.js uses .next directory
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ubuntu/client"
          EXCLUDE: "/.next/, /node_modules/, .env, .env.*, .env.local"